#lanuage
language: python
#version
python:
  - "3.6"
# command to install dependencies
install:
  - pip install
  - pip install -r requirements.txt
  - pip install coveralls
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE test;'
# command to run tests
script: nosetests --exe -v --with-coverage --cover-package=workout

after_success: coveralls